# Always run all cells, starting with module imports such as in the cell below

In [1]:
import numpy as np
from datascience import * # Brings into Python the datascience Table object

# This lines load the tests.
from gofer.ok import check

## Learning from Lab 00/01
Working with Jupyter Notebooks
- Expressions
- Variables & upcoming Data Types
    - Strings
    - Integer
    - Float
- built-in functions: print("Hello World")
- Kernel
- errors
- check work with check('tests/q2_1.py')
- Shortcuts
- Renaming your notebook and exporting to HTML
- Running the tests
- Code vs Markdown cells

### Expressions

In [2]:
# This code below is an expression
c = 212 / 31 + 6

### Variables
#### Strings

In [3]:
first_name = "Darth"
last_name = "Vadar"

print(first_name, last_name)

Darth Vadar


#### Integers

In [4]:
two = 2
two + two

4

In [5]:
type(two)

int

### Floating point numbers

In [6]:
approx_pi = 22 / 7
print(approx_pi)
print(type(approx_pi))

3.142857142857143
<class 'float'>


### Built-in print() function.

In [7]:
print("Welcome to Elements of Data Science!")

Welcome to Elements of Data Science!


## Upcoming Learning Goals from Lab 02
Data Types: See video of same name
- Expressions & numbers revisited
- Variables & Data Types
    - Strings
    - Integer
    - Float
- more built-in functions: max(), min(), abs(), pow(), round()
- Translating science into Python formulas: Newton's equations
- importing code functionality: import math
    - math.pi()
    - math.sqrt()
    - math.log()
    - math.factorial()
- parentheses and order of operations (PEMDAS)
- arrays: from datascience import *
    - make_array(0.125, 4.75, -1.3)
- arrays: import numpy as np
    - np.array([0, 1, -1, math.pi, math.e])
- lists: [1, 2, 3, 4]

### More built-in functions

In [8]:
maximum_number=max(3,4.4)
maximum_number

4.4

### Importing modules to add functionality

In [9]:
import math
radius = 4
area_of_circle = math.pi * radius**2 
print(area_of_circle)

50.26548245743669


In [10]:
math.e

2.718281828459045

In [11]:
area_of_circle = radius**2 * math.pi
area_of_circle

50.26548245743669

### Different ways to import and the risk in using import *

In [12]:
# Plain, vanilla import
import math

# Must preface functions with the whole module name
math.pi

3.141592653589793

In [13]:
# Renaming, often to abbreviate, on import
import math as m

# Now you preface functions with the shorter name
m.pi

3.141592653589793

In [14]:
# Bringing all of the modules functions into your working namespace
from math import *

# Now you don't need any preface to call the functions
pi

3.141592653589793

In [15]:
# The danger of import *
# What if I have a variable name pi
pi = "My favorite is pumpkin!"
pi

'My favorite is pumpkin!'

In [16]:
# Now I import the math module
from math import *

pi

3.141592653589793

In [17]:
# The math module ate my pi!
# I import the other ways, the variable remain distinct
import math

pi = "My favorite is pumpkin!"

print(pi)
print(math.pi)

# The morale of the story is be careful with import * or you might lose your pi!

My favorite is pumpkin!
3.141592653589793


In [18]:
# You can check to see what names will be imported
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

### Parenthesis () and PEMDAS
In standard math notation, the first expression below is

$$6 + 6 \times 5 - 6 \times 3^2 \times \frac{2^3}{4} \times 7,$$

while the second expression below is

$$6 + (6 \times 5 - (6 \times 3))^2 \times (\frac{(2^3)}{4} \times 7).$$



In [19]:
6+6*5-6*3**2*2**3/4*7

-720.0

In [20]:
6+(6*5-(6*3))**2*((2**3)/4*7)

2022.0

### The datascience module

In [24]:
import datascience
dir(datascience)

['Circle',
 'CurrencyFormatter',
 'DateFormatter',
 'DistributionFormatter',
 'Formatter',
 'Map',
 'Marker',
 'NumberFormatter',
 'PercentFormatter',
 'Region',
 'Table',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'are',
 'default_formatter',
 'formats',
 'get_coordinates',
 'is_non_string_iterable',
 'make_array',
 'maps',
 'minimize',
 'percentile',
 'plot_cdf_area',
 'plot_normal_cdf',
 'predicates',
 'proportions_from_distribution',
 'sample_proportions',
 'table_apply',
 'tables',
 'util',
 'version']

In [25]:
# We use this in our class because not that many names are imported,
# and they are names we are unlikely to use ourselves, so the 
# convenience outweighs the risk
from datascience import *

### Arrays
Arrays are sequences of data stored in a variable. All the data in the sequence must be the same data type.

In [27]:
x = make_array([2, 4, 6, 8])
x

array([[2, 4, 6, 8]], dtype=object)

In [28]:
names = make_array(["tacos", "burritoes", "enchiladas"])
names

array([['tacos', 'burritoes', 'enchiladas']], dtype=object)

In [29]:
# Arrays are so useful because we can operate on all of the elements in an array at once
x + 10

array([[12, 14, 16, 18]], dtype=object)

### Lists
Lists are another Python data type that can store a sequence, but the elements of a list do not all have to be the same data type. You cannot operate on all of the elements of a list, like with an array, but they can be useful when your data is heterogeneous.

In [30]:
sample_list = ['Jonathan', 'ate', 100, 'pumpkin pies']
sample_list

['Jonathan', 'ate', 100, 'pumpkin pies']

In [31]:
# Notice that we make arrays by passing a list comprised of one type of data to the make_array() function
x = make_array([2, 4, 6, 8])
x

array([[2, 4, 6, 8]], dtype=object)

## Numpy (short for Numerical Python) 
Numpy is a module that add a lot of functionality for working with array. As scientists, we will us it in virtually every Jupyter notebook. In fact, it is used so commonly that everyone imports it using the abbreviated name np.

In [32]:
import numpy as np

In [36]:
# You can also use numpy to create arrays
key_math_constants = np.array([0, 1, -1, math.pi, math.e])

In [40]:
# importing numpy adds hundreds of functions.
# Here is one example that adds up all the elements of the array
np.sum(key_math_constants)

5.8598744820488378