# Always run all cells, starting with module imports such as in the cell below

In [1]:
import numpy as np
from datascience import * 

## Learning from Lab 00/01
Working with Jupyter Notebooks
- Expressions
- Variables & upcoming Data Types
    - Strings
    - Integer
    - Float
- built-in functions: print("Hello World")
- Kernel
- errors
- check work with check('tests/q2_1.py')
- Shortcuts
- Exporting your notebook to HTML
- Running the tests
- Code vs Markdown cells

### Expressions

In [1]:
# This code below is an expression.
# It assigns a value to the variable c
c = 212 / 31 + 6
c

12.838709677419356

### Variables
#### Strings
Strings variables hold text as a string of characters.

In [2]:
first_name = "Darth"
last_name = "Vadar"

# The print function can take any number of arguments.
print(first_name, last_name)

Darth Vadar


#### Integers

In [4]:
two = 2
two + two

4

In [5]:
# The type() function returns the data type of a variable
type(two)

int

In [6]:
type(first_name)

str

### Floating point numbers
Floating point numbers have a decimal place.

In [7]:
approx_pi = 22 / 7
print(approx_pi)
print(type(approx_pi))

3.142857142857143
<class 'float'>


### More built-in functions

In [8]:
maximum_number = max(3, 4.4)
maximum_number

4.4

### Importing modules to add functionality

In [9]:
import math
radius = 4
area_of_circle = math.pi * radius**2 
print(area_of_circle)

50.26548245743669


In [10]:
math.e

2.718281828459045

### The different ways to import and the risk of using import *

In [8]:
# Plain, vanilla import
import math

# Must preface functions with the whole module name
math.pi

3.141592653589793

In [13]:
# Renaming, often to abbreviate, on import
import math as m

# Now you preface functions with the shorter name
m.pi

3.141592653589793

In [14]:
# Bringing all of the modules functions into your working namespace
from math import *

# Now you don't need any preface to call the functions
pi

3.141592653589793

In [15]:
# The danger of import *
# What if I have a variable name pi
pi = "My favorite is pumpkin!"
pi

'My favorite is pumpkin!'

In [16]:
# Now I import the math module
from math import *
pi

3.141592653589793

In [17]:
# The math module ate my pi!
# If I import the other ways, the variables remain distinct
import math
pi = "My favorite is pumpkin!"
print(pi)
print(math.pi)

# The morale of the story is be careful with import * or you might lose your pi!

My favorite is pumpkin!
3.141592653589793


In [18]:
# You can check to see what names will be imported
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'cbrt',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'exp2',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

Learning how different functions behave is an important part of learning a programming language. A Jupyter notebook can assist in remembering the names and effects of different functions. When editing a code cell, press the tab key after typing the beginning of a name to bring up a list of ways to complete that name. For example, press tab after math. to see all of the functions available in the math module. Typing will narrow down the list of options. To learn more about a function, place a ? after its name. For example, typing math.log? will bring up a description of the log function in the math module.

In [19]:
math.

SyntaxError: invalid syntax (3171735483.py, line 1)

In [20]:
math.log?

Docstring:
log(x, [base=math.e])
Return the logarithm of x to the given base.

If the base not specified, returns the natural logarithm (base e) of x.
Type:      builtin_function_or_method

### The datascience module

In [23]:
import datascience
dir(datascience)

['Circle',
 'CurrencyFormatter',
 'DateFormatter',
 'DistributionFormatter',
 'Formatter',
 'Map',
 'Marker',
 'NumberFormatter',
 'PercentFormatter',
 'Region',
 'Table',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'are',
 'default_formatter',
 'formats',
 'get_coordinates',
 'is_non_string_iterable',
 'make_array',
 'maps',
 'minimize',
 'percentile',
 'plot_cdf_area',
 'plot_normal_cdf',
 'predicates',
 'proportions_from_distribution',
 'sample_proportions',
 'table_apply',
 'tables',
 'util',
 'version']

In [9]:
# We use this in our class because not that many names are imported,
# and they are names we are unlikely to use ourselves, so the 
# convenience outweighs the risk
from datascience import *

### Arrays
Arrays are sequences of data stored in a variable. All the data in the sequence must be the same data type. The `make_array` function is part of the datascience module.

In [25]:
x = make_array([2, 4, 6, 8])
x

array([[2, 4, 6, 8]], dtype=object)

In [26]:
names = make_array(["tacos", "burritoes", "enchiladas"])
names

array([['tacos', 'burritoes', 'enchiladas']], dtype=object)

In [27]:
# Arrays are so useful because we can operate on all of the elements in an array at once
x + 10

array([[12, 14, 16, 18]], dtype=object)

In [28]:
# Square every element in the array
y = x**2
y

array([[4, 16, 36, 64]], dtype=object)

### Lists
Lists are another Python data type that can store a sequence, but the elements of a list do not all have to be the same data type. You cannot operate on all of the elements of a list, like with an array, but they can be useful when your data is heterogeneous.

In [29]:
sample_list = ['Jonathan', 'ate', 100, 'pumpkin pies']
sample_list

['Jonathan', 'ate', 100, 'pumpkin pies']

In [30]:
# Notice that we make arrays by passing a list comprised of one type of data to the make_array() function
x = make_array([2, 4, 6, 8])
x

array([[2, 4, 6, 8]], dtype=object)

## Numpy (short for Numerical Python) 
Numpy is a module that add a lot of functionality for working with array. As scientists, we will us it in virtually every Jupyter notebook. In fact, it is used so commonly that everyone imports it using the abbreviated name np.

In [31]:
import numpy as np

In [32]:
# You can also use numpy to create arrays
key_math_constants = np.array([0, 1, -1, math.pi, math.e])

In [33]:
# importing numpy adds hundreds of functions.
# Here is one example that adds up all the elements of the array
np.sum(key_math_constants)

5.8598744820488378

### Parenthesis () and PEMDAS
In standard math notation, the first expression below is

$$6 + 6 \times 5 - 6 \times 3^2 \times \frac{2^3}{4} \times 7,$$

while the second expression below is

$$6 + (6 \times 5 - (6 \times 3))^2 \times (\frac{(2^3)}{4} \times 7).$$



In [21]:
6 + 6*5 - 6 * 3**2 * 2**3 / 4 * 7

-720.0

In [22]:
6 + (6*5 - (6*3))**2 * ((2**3)/4 * 7)

2022.0