In [2]:
from datascience import *
import numpy as np

Let us create a Table with monthly rainfall data (inch) for Philadelphia 

In [9]:
mytable_1 = Table().with_columns('Month',np.arange(1,13),'Rainfall',[3.13, 2.75,3.96,3.47,3.34,4.04,4.38,4.29,4.40,3.47,2.91,3.97])

In [12]:
mytable_1

Month | Rainfall
1     | 3.13
2     | 2.75
3     | 3.96
4     | 3.47
5     | 3.34
6     | 4.04
7     | 4.38
8     | 4.29
9     | 4.4
10    | 3.47
... (2 rows omitted)

Extract column of rainfall in inches

In [14]:
rain = mytable_1.column('Rainfall')
rain

array([ 3.13,  2.75,  3.96,  3.47,  3.34,  4.04,  4.38,  4.29,  4.4 ,
        3.47,  2.91,  3.97])

In [15]:
cm_to_inch = 2.54 

In [16]:
rain_in_cm = rain * cm_to_inch
rain_in_cm

array([  7.9502,   6.985 ,  10.0584,   8.8138,   8.4836,  10.2616,
        11.1252,  10.8966,  11.176 ,   8.8138,   7.3914,  10.0838])

In [18]:
mytable_1 = mytable_1.with_columns('Rainfall (cm)', rain_in_cm)

In [23]:
myrainarray = mytable_1.column('Rainfall (cm)')
myrainarray

array([  7.9502,   6.985 ,  10.0584,   8.8138,   8.4836,  10.2616,
        11.1252,  10.8966,  11.176 ,   8.8138,   7.3914,  10.0838])

In [24]:
type(myrainarray)

numpy.ndarray

In [25]:
type(mytable_1)

datascience.tables.Table

In [26]:
myrain_list = [3.13, 2.75,3.96,3.47,3.34,4.04,4.38,4.29,4.40,3.47,2.91,3.97]
myrain_list


[3.13, 2.75, 3.96, 3.47, 3.34, 4.04, 4.38, 4.29, 4.4, 3.47, 2.91, 3.97]

In [31]:
[ z    for z in myrain_list  ]

[3.13, 2.75, 3.96, 3.47, 3.34, 4.04, 4.38, 4.29, 4.4, 3.47, 2.91, 3.97]

In [32]:
mytable_1

Month | Rainfall | Rainfall (cm)
1     | 3.13     | 7.9502
2     | 2.75     | 6.985
3     | 3.96     | 10.0584
4     | 3.47     | 8.8138
5     | 3.34     | 8.4836
6     | 4.04     | 10.2616
7     | 4.38     | 11.1252
8     | 4.29     | 10.8966
9     | 4.4      | 11.176
10    | 3.47     | 8.8138
... (2 rows omitted)

In [36]:
mytable_1 = mytable_1.sort('Rainfall (cm)' ,descending=True  )
mytable_1

Month | Rainfall | Rainfall (cm)
9     | 4.4      | 11.176
7     | 4.38     | 11.1252
8     | 4.29     | 10.8966
6     | 4.04     | 10.2616
12    | 3.97     | 10.0838
3     | 3.96     | 10.0584
4     | 3.47     | 8.8138
10    | 3.47     | 8.8138
5     | 3.34     | 8.4836
1     | 3.13     | 7.9502
... (2 rows omitted)

In [51]:
mytable_1.sort('Rainfall (cm)' ,descending=True  ).column('Month')

array([ 9,  7,  8,  6, 12,  3,  4, 10,  5,  1, 11,  2])

In [52]:
mytable_1.sort('Rainfall (cm)' ,descending=True  ).column('Month').item(0)

9

In [39]:
mytable_1.column('Month').item(0)

7

In [43]:
mytable_1.where('Month', are.above(6)).sort('Month')

Month | Rainfall | Rainfall (cm)
7     | 4.38     | 11.1252
8     | 4.29     | 10.8966
9     | 4.4      | 11.176
10    | 3.47     | 8.8138
11    | 2.91     | 7.3914
12    | 3.97     | 10.0838

In [45]:
np.sum(myrainarray)

112.0394

In [46]:
np.mean(myrainarray)

9.3366166666666661

In [47]:
max(myrainarray)

11.176000000000002

In [48]:
min(myrainarray)

6.9850000000000003

In [50]:
min(mytable_1.column('Rainfall (cm)'))

6.9850000000000003