In [1]:
import hashlib
encoded = hashlib.sha1("abcdef") # "abcdef" is the password
encoded.hexdigest()

TypeError: Strings must be encoded before hashing

In [3]:
# importing hashlib for getting sha256() hash function
import hashlib


def hashfile(file):

    # A arbitrary (but fixed) buffer size
    # 65536 = 65536 bytes = 64 kilobytes
    BUF_SIZE = 65536

    # Initializing the sha256() method
    sha256 = hashlib.sha256()

    # Opening the file provided as the first 
    # commandline argument
    with open("q1.txt", 'rb') as f:
        while True:
            # reading data = BUF_SIZE from the 
            # file and saving it in a variable
            data = f.read(BUF_SIZE)

            # True if eof = 1
            if not data:
                break

            # Passing that data to that sh256 hash 
            # function (updating the function with that data)
            sha256.update(data)

    # sha256.hexdigest() hashes all the input data passed
    # to the sha256() via sha256.update()
    # Acts as a finalize method, after which 
    # all the input data gets hashed
    # hexdigest() hashes the data, and returns 
    # the output in hexadecimal format
    return sha256.hexdigest()


# Calling hashfile() function to obtain hash of the file 
# and saving the result in a variable
file_hash = hashfile(sys.argv[1])

print(f"Hash:{file_hash}")

Hash:86b4985ce902442af649967dcf037d3eae4dc17f86b37a2b7acb45a3f3602455


In [43]:
from cryptography.fernet import Fernet
# we will be encrypting the below string.
with open("q1.txt", 'r') as f:
            message = f.read()
print(message)

# generate a key for encryption and decryption
# You can use fernet to generate 
# the key or use random key generator
# here I'm using fernet to generate key

key = Fernet.generate_key()
print('key: ',key)
# Instance the Fernet class with the key

fernet = Fernet(key)

# then use the Fernet class instance 
# to encrypt the string string must
# be encoded to byte string before encryption
encMessage = fernet.encrypt(message.encode())

print("original string: ", message)
print("encrypted string: ", encMessage)

with open("q1_enc.txt", "wb") as file:
    file.write(encMessage)
# decrypt the encrypted string with the 
# Fernet instance of the key,
# that was used for encrypting the string
# encoded byte string is returned by decrypt method,
# so decode it to string with decode methods
decMessage = fernet.decrypt(encMessage).decode()

print("decrypted string: ", decMessage)

with open("q1_enc.txt", 'rb') as f:
            encmessage = f.read()
decMessage = fernet.decrypt(encMessage).decode()

print("\ndecrypted string from file:\n ", decMessage)

There is a correlation between wait time and duration. If we were to do a regression we would find a positive slope when plotting duration on the x axis and wait time on the y axis.
key:  b'qcpYzFmlnKxfx6aKI7TdubfghunxQXi0RebBPC5dvss='
original string:  There is a correlation between wait time and duration. If we were to do a regression we would find a positive slope when plotting duration on the x axis and wait time on the y axis.
encrypted string:  b'gAAAAABnGSaVo5PLZ7ZYHDYc6cD8cFaS0sD0LzL6CKkiGlSFbyztwqvJ3rtoCId2AUfumjfokE35izwTl54mpYT4vzgPgULC4vNeoPeMTG962oH29HRzaGh1eC0PDqKjyHpKs3-fwjCaJ6WccfVHslWwToQf9XLBlOF2AysKJZLqN9lmoLsOfsge8WkyQU94oc6uA9zS3MGCs2oJj1eE1WzHdg7mgGPw5yRN5QYSbpLz-5nUtIR4EZPVec_jJQAtSijinFc8fDS4A6Ezsio8IykRvXu2xOae4is-p6cbgSd0cEpwp4dO1zwP2iTHvAzzH5mCn570WF1I'
decrypted string:  There is a correlation between wait time and duration. If we were to do a regression we would find a positive slope when plotting duration on the x axis and wait time on the y axis.

decrypt

In [44]:
#!pip install -U sentence-transformers

from scipy.spatial import distance
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

# Sample sentence
sentences = ["The data appeared to be corrupted",
                        "We used statistical analysis to find a good value",
                        "The line was straight", "  "]


test = "I learned how to apply regression models to data."
print('Test sentence:',test)
test_vec = model.encode([test])[0]


for sent in sentences:
        similarity_score = 1-distance.cosine(test_vec, model.encode([sent])[0])
        print(f'\nFor {sent}\nSimilarity Score = {similarity_score} ')





Test sentence: I learned how to apply regression models to data.

For The data appeared to be corrupted
Similarity Score = 0.17233974768756344 

For We used statistical analysis to find a good value
Similarity Score = 0.36856285052563553 

For The line was straight
Similarity Score = 0.08502143874828338 

For   
Similarity Score = 0.0935596851575281 


In [54]:
from sentence_transformers import CrossEncoder
import torch
model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-12-v2", default_activation_function=torch.nn.ReLU6())
#model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-12-v2", default_activation_function=torch.nn.Sigmoid())
#model = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-12-v2", default_activation_function=torch.nn.ReLU())
scores = model.predict([
    ("How many people live in Berlin?", "Berlin had a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers."),
    ("How many people live in Berlin?", "Berlin is well known for its museums."),
])
# => array([0.9998173 , 0.01312432], dtype=float32)
scores

array([6., 0.], dtype=float32)

In [55]:
scores

array([6., 0.], dtype=float32)

In [58]:
scores = model.predict([
    (decMessage, sentences[0]),
    (decMessage, "Berlin is well known for its museums."),
])
question = 'What trend do you see in the data? Discuss and include an estimate of the the slope'
sentences = ["The data appeared to be corrupted",
                        "We used statistical analysis to find a good value",
                        "The line was straight with a positive slope","Today is a nice day","Confused","There is a correlation between wait time and duration."]

scores = []
print('++++++\n',decMessage,'\n++++\n')
for sent in sentences:
    score = model.predict((decMessage, sent))/6
    print(f'{sent}\n score: {score}\n----')
    scores.append(score)
scores/max(scores)

++++++
 There is a correlation between wait time and duration. If we were to do a regression we would find a positive slope when plotting duration on the x axis and wait time on the y axis. 
++++

The data appeared to be corrupted
 score: 0.24462664127349854
----
We used statistical analysis to find a good value
 score: 0.48777047793070477
----
The line was straight with a positive slope
 score: 0.7215702533721924
----
Today is a nice day
 score: 0.2027327617009481
----
Confused
 score: 0.30788413683573407
----
There is a correlation between wait time and duration.
 score: 1.0
----


array([0.24462664, 0.48777048, 0.72157025, 0.20273276, 0.30788414,
       1.        ])