## Always run all of the notebook starting at the top. 

In [1]:
# Loads the numerical python module
import numpy as np

# Brings into Python the datascience Table object
from datascience import * 

## Lesson Learned from Lab 00/01
Working with Jupyter Notebooks
- Expressions
- Variables & upcoming Data Types
    - Strings
    - Integer
    - Float
- built-in functions: print("Hello World")
- Kernel
- errors
- check work with check('tests/q2_1.py')
- Shortcuts

## Upcoming Learning Goals from Lab 02
Data Types: See video of same name
- Expressions & numbers revisited
- Variables & Data Types
    - Strings
    - Integer
    - Float
- more built-in functions: max(), min(), abs(), pow(), round()
- Translating science into Python formulas: Newton's equations
- importing code functionality: import math
    - math.pi()
    - math.sqrt()
    - math.log()
    - math.factorial()
- arrays: from datascience import *
    - make_array(0.125, 4.75, -1.3)
- arrays: import numpy as np
    - np.array([0, 1, -1, math.pi, math.e])
- lists: [1, 2, 3, 4]

### Student Challenge 1

Find the value of
$$6 + 6 \times 5 - 3^2 \times \frac{2^3}{4}$$

In [3]:
6 + 6 * 5 - 3**2 * 2**3/4

18.0

Many functions are built into Python, such as max and min

In [4]:
maximum_number = max(3, 4.4, 12, 0, -8)
maximum_number

12

While at other times you must load the functions you need from a module

In [5]:
import math

print(math.pi)

3.141592653589793


### Student Challenge  2

Find the area of a circle with a radius of 4.

So far you know about a couple of python variable types.
* strings
* floating point numbers
* integers

In [7]:
# String
s = "I am a string variable"

# Integer
a = 4

# Float
b = 12.8

In [8]:
# Find the type of a variable
type(b)

float

### Student Challenge 3
Find the type of variable created with you add a (int) and b (float) together.

## Lists
The variables a and b above point to a single value. But Python has several variable types that are collections. One of the most common is a `list`. A list can have any number of elements. It is defined using square brackets with the items in the list separated by commas.

In [9]:
names = ["Sally", "Xavier", "Abby"]
names

['Sally', 'Xavier', 'Abby']

In [10]:
prime_numbers = [1, 2, 3, 5, 7, 11, 13]
prime_numbers

[1, 2, 3, 5, 7, 11, 13]

### Student Challenge 4
Create a mixed list that has numbers and strings.

In [ ]:
mixed_list = ...

### Subscripts
To extract a single element from a list, we subscript it using []. For example, to get the third prime number:

In [12]:
prime_numbers[2]

3

Why 2? Because, **and this is important,** Python numbers list starting with element zero.

In [13]:
prime_numbers[0]

1

### Student challenge 5
Extract the value 11 from the prime_numbers list. Figure out the correct subscript to use.

## Arrays
List can be have value that are different date types. An `array` is similar to a list, but all of the values in an array must be the same data type (all numeric, all string).

In [14]:
odd = make_array(1, 3, 5, 7, 9)
odd

array([1, 3, 5, 7, 9])

Subscripting works the same way

In [15]:
odd[2]

5

What is cool is that you can do math with arrays and it automatically operates on all values -- this is called `broadcasting` an operation across an array.

In [16]:
# Add 10 to every element in the array
odd + 10

array([11, 13, 15, 17, 19])

In [18]:
# Add to array togther
# This only works if the two arrays are the same length
even = make_array(0, 2, 4, 6, 8)
odd + even

array([ 1,  5,  9, 13, 17])

### Student Challenge 6
Multiply the odd and even arrays, store the result, and print the maximum value.

array([ 0,  6, 20, 42, 72])

## Subscripting list and arrays revisited.
We've seen how to extract a single value from an array, but we can also slice out a subsection.

In [20]:
x = make_array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
x_squared = x**2
x_squared

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [21]:
# Slice out the first three numbers
x_squared[0:3]

array([1, 4, 9])

Notice that [0:3] means the zeroth, first and second element of the array. In other words, from zero up to but not including 3.

In [22]:
# Another Example
x_squared[2:5]

array([ 9, 16, 25])

## Subscripting Strings
String variables are just collections of characters. They can be subscripted and sliced.

In [25]:
founder = "Russel Conwell"
print(founder[7])
print(founder[7:])

C
Conwell


Note the slice [7:] didn't specify the second subscript, so it slices to the end.

In [26]:
founder[:6]

'Russel'

If we don't specify the beginning, the slice starts with the zeroth element. In this case above, we are slice from the zeroth characture up to, but not including, the sixth character.

### Student Challenge 7
Slice out "an arrow" from the joke below.

In [ ]:
dad_joke1 = "Time flies like an arrow. Fruit flies like a banana."

### Student Challenge 8
Instead of a string, the dad joke below is stored as a list of words (each of which is a string).

Slice out just the answer part.

In [27]:
dad_joke2 = ["Why", "do", "crabs", "never", "give", "to", "charity?", "Because", "they’re", "shellfish."]
dad_joke2

['Why',
 'do',
 'crabs',
 'never',
 'give',
 'to',
 'charity?',
 'Because',
 'they’re',
 'shellfish.']